package anonimizacja.enums;

public enum FirstTokenType {
    SPACE, KROPKA, PRZECINEK, MYSLNIK, PYTAJNIK, WYKRZYKNIK, SLOWO_ZWYKLE, LICZBA, NASTEPNA_LINIA, L_NAWIAS, P_NAWIAS, L_UKOSNIK, P_UKOSNIK, DWUKROPEK
}
